version: '3'

services:
  primevideopg:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'primevideopg'
    restart: always
    volumes:
      - primevideopg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
volumes:
  primevideopg-data: